version: '3.8'

services:
  db:
    image: postgres:15
    container_name: movie-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: Moviedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./Backend/MovieRecommendationSystem
    container_name: movie-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Moviedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123

    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./Frontend/movie_recomendantion_front
    container_name: movie-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata: